# Generated by Django 5.2.14 on 2026-06-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('legajo', models.AutoField(primary_key=True, serialize=False)),
                ('anio_cursado', models.IntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'aula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tipo_evaluacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'calificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(blank=True, max_length=20, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('medio_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision_factura', models.DateField()),
                ('pagada', models.IntegerField()),
            ],
            options={
                'db_table': 'cuota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('comision', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=30)),
                ('nivel', models.CharField(max_length=30)),
                ('cupo_maximo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoCursaMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
            ],
            options={
                'db_table': 'curso_cursa_materias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoParticipaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'curso_participa_viaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'directivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('legajo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocenteDictaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'docente_dicta_materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField()),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'inscripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'instalacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('carga_horaria', models.IntegerField()),
                ('cantidad_clases', models.IntegerField()),
            ],
            options={
                'db_table': 'materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(max_length=350)),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'noticia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalAdministrativo',
            fields=[
                ('legajo', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'personal_administrativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('legajo', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'preceptor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudViaje',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitud_viaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contacto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorTutoraAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parentesco', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tutor_tutora_alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=60, unique=True)),
                ('contrasenia', models.CharField(max_length=20)),
                ('correo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('motivo', models.TextField()),
            ],
            options={
                'db_table': 'viaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViajeUtilizaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateField()),
            ],
            options={
                'db_table': 'viaje_utiliza_vehiculo',
                'managed': False,
            },
        ),
    ]
