# Generated by Django 4.1.13 on 2026-06-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(db_column='legajo_alumno', on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('docente', models.ForeignKey(db_column='legajo_docente', on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
            ],
        ),
    ]
