# Generated by Django 6.0.6 on 2026-06-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('puesto', models.CharField(max_length=50)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('cv', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_postulacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'postulacion_laboral',
                'managed': False,
            },
        ),
    ]
