# Generated by Django 6.0.6 on 2026-06-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solicitudinscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaDeportiva',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'disciplina_deportiva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocenteDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'docente_disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoPendiente',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField()),
            ],
            options={
                'db_table': 'pago_pendiente',
                'managed': False,
            },
        ),
    ]
