# Generated by Django 6.0.5 on 2026-06-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solicitudinscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arancel',
            fields=[
                ('id_arancel', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'arancel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoPendiente',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField()),
            ],
            options={
                'db_table': 'pago_pendiente',
                'managed': False,
            },
        ),
    ]
