# Generated by Django 6.0.5 on 2026-06-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_arancel_pagopendiente'),
        ('core', '0005_disciplinadeportiva_docentedisciplina_pagopendiente'),
    ]

    operations = [
    ]
