# Generated by Django 4.1.13 on 2026-06-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_disciplinadeportiva_docentedisciplina_pagopendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Tarea', 'Tarea'), ('Evaluación', 'Evaluación')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('programa_publicacion', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Programado', 'Programado')], default='Borrador', max_length=20)),
                ('curso_destinado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_docente', to='core.curso')),
                ('docente', models.ForeignKey(db_column='legajo_docente', on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.materia')),
            ],
            options={
                'db_table': 'tarea',
            },
        ),
    ]
