# Generated by Django 6.0.5 on 2026-06-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260619_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacionAlumno',
            fields=[
                ('id_documentacion', models.AutoField(primary_key=True, serialize=False)),
                ('dni_frente', models.CharField(blank=True, max_length=255, null=True)),
                ('dni_dorso', models.CharField(blank=True, max_length=255, null=True)),
                ('partida_nacimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('certificado_salud', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_envio', models.DateTimeField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documentacion_alumno',
                'managed': False,
            },
        ),
    ]
