# Generated by Django 4.1.13 on 2026-06-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tarea'),
        ('core', '0007_documentacionalumno'),
    ]

    operations = [
    ]
